framework:
    messenger:
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                failure_transport:
                options:
                retry_strategy:
                    max_retries: 3
                    multiplier: 2

            async_email:
                dsn: '%env(EMAIL_TRANSPORT_DSN)%'
                failure_transport: failed_email
                options:
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed_email: '%env(FAILED_EMAIL_TRANSPORT_DSN)%'

        routing:

            App\Message\SendEmailMessage: async_email

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
