framework:
    messenger:

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async_sms:
                dsn: '%env(SMS_TRANSPORT_DSN)%'
                failure_transport: failed_sms
                options:
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed_sms: '%env(FAILED_SMS_TRANSPORT_DSN)%'
        routing:
            App\Message\SendSMSMessage: async_sms

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
