monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    services:
        my_formatter:
            class: Monolog\Formatter\LineFormatter
            arguments:
            - "[%%datetime%%] %%channel%%.%%level_name%%: %%message%% %%context%%\n"
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: main_grouped
                excluded_http_codes: [404, 405]
                buffer_size: 40 # How many messages should be saved? Prevent memory leaks
            main_grouped:
                type: group
                members: [ redisMainHandler, telegramHandler ]
            redisMainHandler:
                type: redis
                redis:
                    host : redis
                    port : 6379
                    database: 0
                    key_name: monolog_main
                level: notice
                formatter: my_formatter
            telegramHandler:
                type: telegram
                level: notice
                channel: "@fu_noa_tst"
                token: 2094027731:AAFU_0Qol1Gn7HKadkNV0sas7vJ4RGGNNaY
                formatter: my_formatter

            doctrineLog_grouped:
                type: group
                members: [ doctrineLogRedisHandler, doctrineLogHandler ]
            doctrineLog:
                type: buffer
                handler: doctrineLog_grouped
                level: debug
                channels: [ doctrine ]
            doctrineLogRedisHandler:
                type: redis
                redis:
                    host: redis
                    port: 6379
                    database: 0
                    key_name: monolog_doctrineLog
                formatter: my_formatter
            doctrineLogHandler:
                type: stream
                path: "%kernel.logs_dir%/doctrine.log"
                formatter: my_formatter

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
